(import scheme chicken.base chicken.port)
(import srfi-18)

(define (make-tunnel-port)
  (let ((buffer '())
        (rev-buff '())
        (closed #f)
        (lock (make-mutex)))
    (let ((this-write (lambda (str)
                        (unless closed
                          (assert (and 'write-char (string? str)))
                          (mutex-lock! lock)
                          (let loop ((rest (string->list str)))
                            (if (null? rest)
                              '()
                              (begin 
                                (set! buffer (cons (car rest) buffer))
                                (loop (cdr rest)))))
                          (mutex-unlock! lock)
                          '())))
          (this-read (lambda ()
                       (if closed
                           #!eof
                           (let ((res #f))
                             (mutex-lock! lock)
                             (if (null? rev-buff)
                                 (if (null? buffer)
                                     (set! res #!eof)
                                     (let ((rev-tmp (reverse buffer)))
                                       (set! rev-buff (cdr rev-tmp))
                                       (set! buffer '())
                                       (set! res (car rev-tmp))))
                                 (let ((tmp (car rev-buff)))
                                   (set! rev-buff (cdr rev-buff))
                                   (set! res tmp)))
                             (mutex-unlock! lock)
                             res))))
          (this-ready? (lambda ()
                         (and (not closed) (not (and (null? rev-buff) (null? buffer))))))
          (this-close (lambda ()
                        (set! closed #t))))
      (values
        (make-input-port this-read this-ready? this-close)
        (make-output-port this-write this-close)))))

